### ISSUE TITLE
Error at first run: 'VersionReply' object has no attribute 'ipc_data'

### ISSUE THREAD

**Issue by MadeInPierre** [chlyz/i3-dynamic-tiling#4]
Hi! 

Thank you for this tool that looks very promising. I just tried to execute the `i3ipc-dynamic-tiling` executable (and the python script as well) just after cloning the repo and immediately got this error (no arguments):

```sh
$ ./i3ipc-dynamic-tiling
Traceback (most recent call last):
  File "./i3ipc_dynamic_tiling.py", line 1236, in <module>
    init(IPC)
  File "./i3ipc_dynamic_tiling.py", line 1140, in init
    version = ipc.get_version().ipc_data
AttributeError: 'VersionReply' object has no attribute 'ipc_data'
```

Would you know where this comes from? This may be an issue with versions, but I'm not sure. Thanks!

**Comment by chlyz** [comment]
Thank you for your report.

 What version of i3/sway are you using. There are are some differences in how the ipc is working between different versions and especially between i3 and sway, where sway sometimes does things differently and changes it later.

The line that you point out is just an attempt to check whether it is sway or i3 that is in use.

**Comment by MadeInPierre** [comment]
Thank you for your reply. I am using i3 `4.19.1 (2021-02-01)`.

**Comment by chlyz** [comment]
Hmm, I am currently using 4.19.2 (git) so it should not be that. What is your python i3ipc version? I am using 2.2.1.
